### ISSUE TITLE
Can you provide an example or a processed result in the data preprocessing section?

### ISSUE THREAD

**Issue by Pang-b0** [Ruixxxx/SGDA#2]
Thank you for your paper. Can you provide an example or a processed result in the data preprocessing section? I can't seem to realize and handle it according to the prompt of the code.

**Comment by Ruixxxx** [comment]
> Thank you for your paper. Can you provide an example or a processed result in the data preprocessing section? I can't seem to realize and handle it according to the prompt of the code.

Thank you for your attention. You may refer to Fig. 6 in our paper.
